-- Alter users table
ALTER TABLE users
ADD COLUMN gender SMALLINT NOT NULL,
ADD COLUMN age int NOT NULL;

CREATE TABLE IF NOT EXISTS chat_sessions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    chat_id         VARCHAR(255)                              NOT NULL,
    user_id         BIGINT                                    NOT NULL,
    start_time      TIMESTAMP WITH TIME ZONE                  NOT NULL,
    end_time        TIMESTAMP WITH TIME ZONE                  NOT NULL,
    CONSTRAINT pk_chat_sessions PRIMARY KEY (id),
    CONSTRAINT fk_chat_sessions_users
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- Create tts table
CREATE TABLE IF NOT EXISTS tts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    chat_session_id BIGINT                                    NOT NULL,
    read_speed      FLOAT                                     NOT NULL,
    detail_level    INTEGER                                   NOT NULL,
    briefing_count  INTEGER                                   NOT NULL,
    CONSTRAINT pk_tts PRIMARY KEY (id),
    CONSTRAINT fk_tts_chat_session
        FOREIGN KEY (chat_session_id)
        REFERENCES chat_sessions(id)
        ON DELETE CASCADE
);