CREATE TABLE IF NOT EXISTS summarized_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    summary TEXT NOT NULL,
    CONSTRAINT pk_summarized_articles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS article_summarized_articles (
    article_id BIGINT NOT NULL,
    summarized_article_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, summarized_article_id),
    CONSTRAINT fk_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_summarized_article FOREIGN KEY (summarized_article_id) REFERENCES summarized_articles (id) ON DELETE CASCADE
);
