version: '3'
services:
  artemis:
    image: apache/activemq-artemis
    ports:
      - "61616:61616" # JMS
      - "8161:8161" # Web Console
      - "61613:61613" # STOMP
    container_name: activemq-container
    environment:
      - ARTEMIS_USER=${ARTEMIS_USER}
      - ARTEMIS_PASSWORD=${ARTEMIS_PASSWORD}
    restart: always
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-container
    environment:
      - POSTGRES_URL=${DB_URL}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - REDIS_USERNAME=${REDIS_USERNAME}
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   container_name: redis-container
  #   volumes:
  #     - redis_data:/data
  #   restart: always
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    restart: always
volumes:
  postgres_data:
    name: "postgres_data"
  redis_data:
    name: "redis_data"
  mongodb_data:
    name: "mongodb_data"

